language: python
 - "3.6"

script:
 - tests/test_shoppinglist.py

before_install:
 - chmod +x tests/test_shoppinglist.py

# whitelist
branches:
  only:
    - master

#dependacies and libraries to install
install: pip install -r requirements.txt